apiVersion: v1
kind: ConfigMap
metadata:
  name: bytebook-config
  namespace: bytebook
  labels:
    app.kubernetes.io/name: bytebook
    app.kubernetes.io/component: config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  Redis__ConnectionString: "bytebook-redis:6379"